CREATE TABLE IF NOT EXISTS admins(id serial PRIMARY KEY, login VARCHAR(255) UNIQUE NOT NULL, password VARCHAR(255) UNIQUE NOT NULL, is_super BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS projects (
    Id BIGINT NOT NULL,
    schema JSON NOT NULL,
    pub_key VARCHAR(512) NOT NULL,
    priv_key VARCHAR(512) NOT NULL,
    adminId BIGINT NOT NULL,
    name VARCHAR(63) NOT NULL,
    PRIMARY KEY (Id));